/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf -t
Author: GORDEYKOMARK (https://sketchfab.com/gordeykomark)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-porsche-911-rwb-993-523206619f5f4234aea72dc9305bb11a
Title: [FREE] Porsche 911 RWB (993)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mirror_Mirror_0: THREE.Mesh
    Hood_car_logo_Car_logo_0: THREE.Mesh
    Steering_wheel_car_logo_Car_logo_0: THREE.Mesh
    Headlights_main_Headlights_0: THREE.Mesh
    Headlights_main_Headlights_N_0: THREE.Mesh
    Headlights_glass_Headlights_glass_0: THREE.Mesh
    Lenses_Lenses_0: THREE.Mesh
    Chrome_Main_0: THREE.Mesh
    Chrome_Normals_0: THREE.Mesh
    Taillights_NM_Taillights_glass_N_0: THREE.Mesh
    Taillights_glass_Taillights_glass_0: THREE.Mesh
    Taillights_glass_Taillights_clear001_0: THREE.Mesh
    Interior_Interior_main_0: THREE.Mesh
    Interior_Leather_0: THREE.Mesh
    Interior_Carbon_fiber_0: THREE.Mesh
    Interior_Screen_0: THREE.Mesh
    Interior_Soft_plastic_0: THREE.Mesh
    Interior_Interior_metal_0: THREE.Mesh
    Interior_speedometer_arrows001_0: THREE.Mesh
    Interior_Speedometer_glass_0: THREE.Mesh
    Windows_Window_0: THREE.Mesh
    Window_circuit_Glossy_black_0: THREE.Mesh
    Inners_Rough_black_0: THREE.Mesh
    Windshield_shit_Visor_0: THREE.Mesh
    Rubber_Rubber_0: THREE.Mesh
    Body_Paint_0: THREE.Mesh
    Grille_mesh_Bumper_mesh_0: THREE.Mesh
    Blinkers_glass_foggers_glass_0: THREE.Mesh
    Blinkers_bulb_Blinkers_bulb_0: THREE.Mesh
    Sunroof_Sunroof_0: THREE.Mesh
    hook_Red_0: THREE.Mesh
    ['1st_inners_Zero_black_0']: THREE.Mesh
    Skirts001_Kit_color_0: THREE.Mesh
    FR_caliper_caliper_main_0: THREE.Mesh
    FR_caliper_Brake_disk_0: THREE.Mesh
    FR_caliper_Spacer_0: THREE.Mesh
    Muffler_Exhaust_muffler_metal_0: THREE.Mesh
    Exhaust_tips_Tips_inner_0: THREE.Mesh
    Exhaust_tips_Exhaust_tips_metal_0: THREE.Mesh
    Door_chrome_Exhaust_tips_metal_0: THREE.Mesh
    Tire_Tire001_0: THREE.Mesh
    Wheel_screws002_Rim_chrome_shelf_0: THREE.Mesh
    RL_wheel_Rim_chrome_shelf_0: THREE.Mesh
    RL_wheel_Rim_0: THREE.Mesh
    Tire001_Tire001_0: THREE.Mesh
    Wheel_screws001_Rim_chrome_shelf_0: THREE.Mesh
    FL_wheel_Rim_chrome_shelf_0: THREE.Mesh
    FL_wheel_Rim_0: THREE.Mesh
    FL_brakes_Spacer_0: THREE.Mesh
    FL_brakes_Brake_disk_0: THREE.Mesh
    RR_caliper_caliper_main_0: THREE.Mesh
    RR_caliper_Brake_disk_0: THREE.Mesh
    RR_caliper_Spacer_0: THREE.Mesh
    RL_brakes_Spacer_0: THREE.Mesh
    RL_brakes_Brake_disk_0: THREE.Mesh
    Tire002_Tire001_0: THREE.Mesh
    Wheel_screws003_Rim_chrome_shelf_0: THREE.Mesh
    FR_wheel_Rim_chrome_shelf_0: THREE.Mesh
    FR_wheel_Rim_0: THREE.Mesh
    FR_brakes_Spacer_0: THREE.Mesh
    FR_brakes_Brake_disk_0: THREE.Mesh
    Tire003_Tire001_0: THREE.Mesh
    Wheel_screws_Rim_chrome_shelf_0: THREE.Mesh
    RR_wheel_Rim_chrome_shelf_0: THREE.Mesh
    RR_wheel_Rim_0: THREE.Mesh
    RR_brakes_Spacer_0: THREE.Mesh
    RR_brakes_Brake_disk_0: THREE.Mesh
    L_screws_Kit_color_0: THREE.Mesh
    FL_caliper_caliper_main_0: THREE.Mesh
    FL_caliper_Brake_disk_0: THREE.Mesh
    FL_caliper_Spacer_0: THREE.Mesh
    RL_caliper_caliper_main_0: THREE.Mesh
    RL_caliper_Brake_disk_0: THREE.Mesh
    RL_caliper_Spacer_0: THREE.Mesh
    R_screws_Kit_color_0: THREE.Mesh
  }
  materials: {
    Mirror: THREE.MeshStandardMaterial
    Car_logo: THREE.MeshStandardMaterial
    Headlights: THREE.MeshStandardMaterial
    Headlights_N: THREE.MeshStandardMaterial
    Headlights_glass: THREE.MeshStandardMaterial
    Lenses: THREE.MeshPhysicalMaterial
    Main: THREE.MeshStandardMaterial
    Normals: THREE.MeshStandardMaterial
    Taillights_glass_N: THREE.MeshStandardMaterial
    Taillights_glass: THREE.MeshPhysicalMaterial
    ['Taillights_clear.001']: THREE.MeshPhysicalMaterial
    Interior_main: THREE.MeshStandardMaterial
    Leather: THREE.MeshStandardMaterial
    Carbon_fiber: THREE.MeshStandardMaterial
    Screen: THREE.MeshStandardMaterial
    Soft_plastic: THREE.MeshStandardMaterial
    Interior_metal: THREE.MeshStandardMaterial
    ['speedometer_arrows.001']: THREE.MeshStandardMaterial
    Speedometer_glass: THREE.MeshPhysicalMaterial
    Window: THREE.MeshStandardMaterial
    Glossy_black: THREE.MeshStandardMaterial
    Rough_black: THREE.MeshStandardMaterial
    Visor: THREE.MeshStandardMaterial
    Rubber: THREE.MeshStandardMaterial
    Paint: THREE.MeshStandardMaterial
    Bumper_mesh: THREE.MeshStandardMaterial
    foggers_glass: THREE.MeshPhysicalMaterial
    Blinkers_bulb: THREE.MeshStandardMaterial
    Sunroof: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    Zero_black: THREE.MeshStandardMaterial
    Kit_color: THREE.MeshStandardMaterial
    caliper_main: THREE.MeshStandardMaterial
    Brake_disk: THREE.MeshStandardMaterial
    Spacer: THREE.MeshStandardMaterial
    Exhaust_muffler_metal: THREE.MeshStandardMaterial
    Tips_inner: THREE.MeshStandardMaterial
    Exhaust_tips_metal: THREE.MeshStandardMaterial
    ['Tire.001']: THREE.MeshStandardMaterial
    Rim_chrome_shelf: THREE.MeshStandardMaterial
    material_39: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/car/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.546}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Mirror_Mirror_0.geometry} material={materials.Mirror} scale={200} />
          <group scale={200}>
            <mesh geometry={nodes.Hood_car_logo_Car_logo_0.geometry} material={materials.Car_logo} />
            <mesh geometry={nodes.Steering_wheel_car_logo_Car_logo_0.geometry} material={materials.Car_logo} position={[0.27, 0.64, 0.249]} rotation={[2.355, 0, Math.PI]} scale={0.468} />
          </group>
          <group scale={200}>
            <mesh geometry={nodes.Headlights_main_Headlights_0.geometry} material={materials.Headlights} />
            <mesh geometry={nodes.Headlights_main_Headlights_N_0.geometry} material={materials.Headlights_N} />
            <mesh geometry={nodes.Headlights_glass_Headlights_glass_0.geometry} material={materials.Headlights_glass} />
            <mesh geometry={nodes.Lenses_Lenses_0.geometry} material={materials.Lenses} />
          </group>
          <group scale={200}>
            <group position={[0, 0, -0.001]}>
              <mesh geometry={nodes.Taillights_glass_Taillights_glass_0.geometry} material={materials.Taillights_glass} />
              <mesh geometry={nodes.Taillights_glass_Taillights_clear001_0.geometry} material={materials['Taillights_clear.001']} />
            </group>
            <mesh geometry={nodes.Chrome_Main_0.geometry} material={materials.Main} />
            <mesh geometry={nodes.Chrome_Normals_0.geometry} material={materials.Normals} />
            <mesh geometry={nodes.Taillights_NM_Taillights_glass_N_0.geometry} material={materials.Taillights_glass_N} />
          </group>
          <group scale={200}>
            <mesh geometry={nodes.Interior_Interior_main_0.geometry} material={materials.Interior_main} />
            <mesh geometry={nodes.Interior_Leather_0.geometry} material={materials.Leather} />
            <mesh geometry={nodes.Interior_Carbon_fiber_0.geometry} material={materials.Carbon_fiber} />
            <mesh geometry={nodes.Interior_Screen_0.geometry} material={materials.Screen} />
            <mesh geometry={nodes.Interior_Soft_plastic_0.geometry} material={materials.Soft_plastic} />
            <mesh geometry={nodes.Interior_Interior_metal_0.geometry} material={materials.Interior_metal} />
            <mesh geometry={nodes.Interior_speedometer_arrows001_0.geometry} material={materials['speedometer_arrows.001']} />
            <mesh geometry={nodes.Interior_Speedometer_glass_0.geometry} material={materials.Speedometer_glass} />
            <mesh geometry={nodes.Windows_Window_0.geometry} material={materials.Window} />
            <mesh geometry={nodes.Window_circuit_Glossy_black_0.geometry} material={materials.Glossy_black} />
            <mesh geometry={nodes.Inners_Rough_black_0.geometry} material={materials.Rough_black} />
            <mesh geometry={nodes.Windshield_shit_Visor_0.geometry} material={materials.Visor} />
          </group>
          <mesh geometry={nodes.Rubber_Rubber_0.geometry} material={materials.Rubber} scale={200} />
          <group scale={200}>
            <mesh geometry={nodes.Body_Paint_0.geometry} material={materials.Paint} />
            <mesh geometry={nodes.Grille_mesh_Bumper_mesh_0.geometry} material={materials.Bumper_mesh} />
            <mesh geometry={nodes.Blinkers_glass_foggers_glass_0.geometry} material={materials.foggers_glass} />
            <mesh geometry={nodes.Blinkers_bulb_Blinkers_bulb_0.geometry} material={materials.Blinkers_bulb} />
            <mesh geometry={nodes.Sunroof_Sunroof_0.geometry} material={materials.Sunroof} />
          </group>
          <mesh geometry={nodes.hook_Red_0.geometry} material={materials.material} scale={200} />
          <mesh geometry={nodes['1st_inners_Zero_black_0'].geometry} material={materials.Zero_black} scale={200} />
          <mesh geometry={nodes.Skirts001_Kit_color_0.geometry} material={materials.Kit_color} scale={200} />
          <group position={[-140.964, 44.291, 259.146]} rotation={[-Math.PI, 0.347, Math.PI]} scale={193.185}>
            <mesh geometry={nodes.FR_caliper_caliper_main_0.geometry} material={materials.caliper_main} />
            <mesh geometry={nodes.FR_caliper_Brake_disk_0.geometry} material={materials.Brake_disk} />
            <mesh geometry={nodes.FR_caliper_Spacer_0.geometry} material={materials.Spacer} />
          </group>
          <mesh geometry={nodes.Muffler_Exhaust_muffler_metal_0.geometry} material={materials.Exhaust_muffler_metal} scale={200} />
          <group scale={200}>
            <group position={[-0.005, 0.115, -1.916]} rotation={[-0.116, 0, 0]}>
              <mesh geometry={nodes.Exhaust_tips_Tips_inner_0.geometry} material={materials.Tips_inner} />
              <mesh geometry={nodes.Exhaust_tips_Exhaust_tips_metal_0.geometry} material={materials.Exhaust_tips_metal} />
            </group>
            <mesh geometry={nodes.Door_chrome_Exhaust_tips_metal_0.geometry} material={materials.Exhaust_tips_metal} position={[-0.005, 0.115, -1.916]} rotation={[-0.116, 0, 0]} />
          </group>
          <group position={[171.477, 39.77, -228.741]} rotation={[-0.383, 0, 0]} scale={2.428}>
            <mesh geometry={nodes.RL_wheel_Rim_chrome_shelf_0.geometry} material={materials.Rim_chrome_shelf} />
            <mesh geometry={nodes.RL_wheel_Rim_0.geometry} material={materials.material_39} />
            <mesh geometry={nodes.Tire_Tire001_0.geometry} material={materials['Tire.001']} position={[2.167, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.008} />
            <mesh geometry={nodes.Wheel_screws002_Rim_chrome_shelf_0.geometry} material={materials.Rim_chrome_shelf} />
          </group>
          <group position={[162.941, 40.634, 235.089]} rotation={[0, -0.348, 0]} scale={2.428}>
            <mesh geometry={nodes.FL_wheel_Rim_chrome_shelf_0.geometry} material={materials.Rim_chrome_shelf} />
            <mesh geometry={nodes.FL_wheel_Rim_0.geometry} material={materials.material_39} />
            <mesh geometry={nodes.Tire001_Tire001_0.geometry} material={materials['Tire.001']} position={[2.388, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.008} />
            <mesh geometry={nodes.Wheel_screws001_Rim_chrome_shelf_0.geometry} material={materials.Rim_chrome_shelf} />
          </group>
          <group position={[142.426, 40.505, 226.677]} rotation={[Math.PI / 2, 0, -2.794]} scale={1.798}>
            <mesh geometry={nodes.FL_brakes_Spacer_0.geometry} material={materials.Spacer} />
            <mesh geometry={nodes.FL_brakes_Brake_disk_0.geometry} material={materials.Brake_disk} />
          </group>
          <group position={[1.848, 43.589, -201.148]} rotation={[-Math.PI, 0, -Math.PI]} scale={181.904}>
            <mesh geometry={nodes.RR_caliper_caliper_main_0.geometry} material={materials.caliper_main} />
            <mesh geometry={nodes.RR_caliper_Brake_disk_0.geometry} material={materials.Brake_disk} />
            <mesh geometry={nodes.RR_caliper_Spacer_0.geometry} material={materials.Spacer} />
          </group>
          <group position={[146.929, 38.595, -237.01]} rotation={[Math.PI / 2, 0, Math.PI]} scale={1.724}>
            <mesh geometry={nodes.RL_brakes_Spacer_0.geometry} material={materials.Spacer} />
            <mesh geometry={nodes.RL_brakes_Brake_disk_0.geometry} material={materials.Brake_disk} />
          </group>
          <group position={[-149.648, 40.721, 225.688]} rotation={[-Math.PI, 0.347, Math.PI]} scale={2.428}>
            <mesh geometry={nodes.FR_wheel_Rim_chrome_shelf_0.geometry} material={materials.Rim_chrome_shelf} />
            <mesh geometry={nodes.FR_wheel_Rim_0.geometry} material={materials.material_39} />
            <mesh geometry={nodes.Tire002_Tire001_0.geometry} material={materials['Tire.001']} position={[5.313, -0.036, -0.008]} rotation={[Math.PI / 2, 0, 0]} scale={0.008} />
            <mesh geometry={nodes.Wheel_screws003_Rim_chrome_shelf_0.geometry} material={materials.Rim_chrome_shelf} position={[2.925, -0.036, -0.008]} />
          </group>
          <group position={[-135.812, 40.505, 231.685]} rotation={[Math.PI / 2, 0, 0.347]} scale={1.798}>
            <mesh geometry={nodes.FR_brakes_Spacer_0.geometry} material={materials.Spacer} />
            <mesh geometry={nodes.FR_brakes_Brake_disk_0.geometry} material={materials.Brake_disk} />
          </group>
          <group position={[-172.459, 39.77, -228.772]} rotation={[-2.759, 0, -Math.PI]} scale={2.428}>
            <mesh geometry={nodes.RR_wheel_Rim_chrome_shelf_0.geometry} material={materials.Rim_chrome_shelf} />
            <mesh geometry={nodes.RR_wheel_Rim_0.geometry} material={materials.material_39} />
            <mesh geometry={nodes.Tire003_Tire001_0.geometry} material={materials['Tire.001']} position={[2.167, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.008} />
            <mesh geometry={nodes.Wheel_screws_Rim_chrome_shelf_0.geometry} material={materials.Rim_chrome_shelf} />
          </group>
          <group position={[-147.911, 38.595, -220.504]} rotation={[Math.PI / 2, 0, 0]} scale={1.724}>
            <mesh geometry={nodes.RR_brakes_Spacer_0.geometry} material={materials.Spacer} />
            <mesh geometry={nodes.RR_brakes_Brake_disk_0.geometry} material={materials.Brake_disk} />
          </group>
          <group position={[128.176, 44.291, 252.838]} rotation={[-Math.PI, 0.348, Math.PI]} scale={193.185}>
            <mesh geometry={nodes.FL_caliper_caliper_main_0.geometry} material={materials.caliper_main} />
            <mesh geometry={nodes.FL_caliper_Brake_disk_0.geometry} material={materials.Brake_disk} />
            <mesh geometry={nodes.FL_caliper_Spacer_0.geometry} material={materials.Spacer} />
          </group>
          <group position={[1.848, 43.589, -201.148]} rotation={[-Math.PI, 0, -Math.PI]} scale={181.904}>
            <mesh geometry={nodes.RL_caliper_caliper_main_0.geometry} material={materials.caliper_main} />
            <mesh geometry={nodes.RL_caliper_Brake_disk_0.geometry} material={materials.Brake_disk} />
            <mesh geometry={nodes.RL_caliper_Spacer_0.geometry} material={materials.Spacer} />
          </group>
          <mesh geometry={nodes.L_screws_Kit_color_0.geometry} material={materials.Kit_color} position={[151.306, 88.135, -353.886]} rotation={[-0.521, -0.458, 0.407]} scale={200} />
          <mesh geometry={nodes.R_screws_Kit_color_0.geometry} material={materials.Kit_color} position={[-151.259, 88.135, -353.886]} rotation={[-0.521, 0.458, -0.407]} scale={[-200, 200, 200]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
